library(stringr)
library(readxl)
help(readxl)
dim(listings)
names(listings)
summary(listings)
df_listings<- readxl:: read_xlsx(path = "listings.xlsx")
read.csv(listings)
summary(df_listings)
variable1<- (df_listings$minimum_nights)
mean(variable1)             
median(variable1)
var(variable1)
